### ISSUE TITLE
Karma / Jasmine Setup Guide

### ISSUE THREAD

**Issue by JacobSiegle** [angular-extensions/pretty-html-log#13]
Great idea to have this auto patching console!

I would like to replace a custom solution in my project with this but unfortunately i'm stuck with karma/jasmine for a while. Any guidance on setting it up with that combo or does this explicitly link into some Jest functionality? Docs say **"This module is best used with Angular and Jest."**.

I tried importing into karma/jasmine using the file param with no luck. Types needed to manually added in tsconfig also in this scenario, but maybe that would be alleviated with proper config.

**Comment by kreuzerk** [comment]
The module was build and tested for Jest, although it should theoretically also work with Karma / Jasmine. I once had it working and I think to remember that the colors were not correctly printed. 
Furthermore, I guess it makes a difference if you run your tests against a real browser or a headless browser. From my point of view, this module makes only sense against headless browser, with a real browser you can debug directly in Chrome.

If I find time I will check if I can make a quick example on how to use with Karma / Jasmine.

**Comment by maxfriedmann** [comment]
@JacobSiegle, do you have problems to get the command itself working or is it not printing well? I had some problems setting things up in our nx workspace, so I asked if they can export the command as a simple function, see https://github.com/angular-extensions/pretty-html-log/pull/24 now its working for me!

**Comment by JacobSiegle** [comment]
Thanks seems i'm able to get it working now also!

**Comment by kreuzerk** [comment]
Glad to hear that its working. @maxfriedmann So this basically means that it works for Jasmine with the `logNgHTML` function but not with the console patch? If yes I would update the Docs accordingly

**Comment by maxfriedmann** [comment]
I am not using Jasmine, but @JacobSiegle  does. In my context, an [nx workspace](https://nx.dev), the console patch doesn't work, but the direct usage works. Nx is great, but it uses a complex tsconfig->extends->tsconfig structure, not sure why it doesn't work. I would bet on myself and my project setup.

**Comment by kreuzerk** [comment]
I am not sure I also have a project where the console patch doesn't work - I hope I find some time to investigate this because I think it is very useful. You can log something and don't have to remove and import statement afterward.
