### ISSUE TITLE
NPM Packaging broken for versions 3.0.0 and up

### ISSUE THREAD

**Issue by johnmcase** [angular-extensions/pretty-html-log#14]
I recently have started to try to use your library in my Angular 8 application that already is testing with Jest.  I pulled the latest version and it did not work.  After a bunch of digging I discovered that all of the .js files in the npm package were empty.  The typings files were all there so it looks good in the IDE but as soon as I run the test I get errors saying that logNgHTML is not a function.

I kept backup up my version until I found one that worked.  Had to go all the way back to 2.0.0

**Comment by kreuzerk** [comment]
With version 3 we updated to Angular 9. Not only do we support Angular 9 but we also updated the internals for Angular 9. See no the (release notes)[https://github.com/angular-extensions/pretty-html-log/releases].

For Angular 8 you should still use version 2.0.0
