### ISSUE TITLE
logNgHTML is not a function

### ISSUE THREAD

**Issue by diegorodridev** [angular-extensions/pretty-html-log#20]
I am having an strange error when trying to use this extension as part of my angular-jest testing environment. 

I have done the following initial setup:

- Installed your extension.
- Reference in setupJest.js
```
import 'jest-preset-angular';
import './jest-global-mocks.ts'; 
import '@angular-extensions/pretty-html-log';
```
 
I have this environment in package.json
```
{
"@angular-extensions/pretty-html-log": "^3.1.1"
"@types/jest": "^26.0.9",
"@angular/cli": "^9.1.11",
"@angular/compiler-cli": "^9.1.12",
"@babel/core": "^7.11.1",
"@babel/preset-env": "^7.11.0",
"babel-jest": "^26.3.0",
}
```
The estrange thing comes now, if I execute just console.logNgHTM(); Throws an error and says that it is missing parameters, this is the expected behaviour for an empty call. However, If I provide either console.logNgHTM(fixture) || console.logNgHTM(component), where component is the actual component being tested, it fails saying:

> TypeError: console.logNgHTML is not a function

What am I missing? Any ideas?

**Comment by daiyis** [comment]
I am having the exact same error, Is there any secret setup?

**Comment by kreuzerk** [comment]
Try adding your setupJest.ts to your tsconfig.spec.ts.

// file src/tsconfig.spec.ts. If the baseUrl is ./src, it has to point to ../jest.setup.ts (out of src)
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/spec",
    "types": ["jest", "node"],
    "esModuleInterop": true
  },
  "files": ["polyfills.ts", "../jest.setup.ts"],
  "include": ["**/*.spec.ts", "**/*.d.ts"]
}

**Comment by kreuzerk** [comment]
I will try to add this to the docs.

**Comment by daiyis** [comment]
> Try adding your setupJest.ts to your tsconfig.spec.ts.

This seems doesn't solve the problem, and I suppose you are referring to the setupJest.ts file not jest.setup.ts in the sample code.

But It still failed with the same error message, though autocompletion is working fine.

**Comment by diegorodridev** [comment]
Thank you for the answer @kreuzerk  but I still have the same problem. I have had that configuration since the beginning, but it doesn't work.

**Comment by kreuzerk** [comment]
@daiyis and @diegorodridev thanks a lot for the feedback - is there a reproduction repo for this issue?
