### ISSUE TITLE
Property 'logNgHTML' does not exist on type 'Console'.

### ISSUE THREAD

**Issue by DeveloperDavo** [angular-extensions/pretty-html-log#3]
```
Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    src/app/app.component.test.ts:17:13 - error TS2339: Property 'logNgHTML' does not exist on type 'Console'.

    17     console.logNgHTML(fixture);
```

In `setupJest.ts` I have:
```
import 'jest-preset-angular';
import '@angular-extensions/pretty-html-log';
```

**Comment by kreuzerk** [comment]
Hi @DeveloperDavo how do you run your tests, over some IDEA or just from command line?

**Comment by DeveloperDavo** [comment]
From the command line

**Comment by kreuzerk** [comment]
@DeveloperDavo, unfortunately, I can not reproduce this. I just tried out the library in a new project with Jest. Is there a link to a repo for reproduction?

**Comment by tonivj5** [comment]
It works perfect to me too :+1:

**Comment by DeveloperDavo** [comment]
Ok I'll have another look during the week. Thanks for checking it out.

**Comment by tonivj5** [comment]
Try adding your `setupJest.ts` to your tsconfig.spec.ts. I have it so:
```ts
// file src/tsconfig.spec.ts. My baseUrl is ./src, so I have to point to ../jest.setup.ts (out of src)
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/spec",
    "types": ["jest", "node"],
    "esModuleInterop": true
  },
  "files": ["polyfills.ts", "../jest.setup.ts"],
  "include": ["**/*.spec.ts", "**/*.d.ts"]
}

```

**Comment by DeveloperDavo** [comment]
Sorry, I don't seem to have access to the code anymore. I'll give it another go in the near future. Since no one else seems to be having the same problem, I'll close it.
