### ISSUE TITLE
Be able to remove comments

### ISSUE THREAD

**Issue by tonivj5** [angular-extensions/pretty-html-log#4]
I would love to remove comments from log because it results very annoying :crying_cat_face:
![image](https://user-images.githubusercontent.com/7110786/75099834-a8acbd80-55c6-11ea-8bea-8b63b7dd54e8.png)

**Comment by tomastrajan** [comment]
@tonivj5 would be a nice feature to have, just to be aware that comments are like hooks for Angular template engine to render something based on some conditions so sometimes they do provide useful information :)

**Comment by kreuzerk** [comment]
I would imagine a flag that allows you to turn them off or on. So maybe by default off, and if you want you can pass the flag to get them

**Comment by tonivj5** [comment]
Yeah @tomastrajan, I know :-) But, sometimes I want to see the template generated and the comments doesn't help me :sweat_smile:

A flag should be perfect! :+1:
