### ISSUE TITLE
Run html through prettier if available

### ISSUE THREAD

**Issue by zakhenry** [angular-extensions/pretty-html-log#6]
while the output is way more awesome than the default, it would be even awesomer if it could detect that prettier is being used (or somehow configured?) and run the html snippet through prettier so that the template looks like how the template was originally written in the source, i.e. prettily.

**Comment by kreuzerk** [comment]
Great idea. The highlight function of pretty-html-log which is used internally already uses prettier. However, currently, I think it doesn't pick up your prettier config. This would definitely be something to add.

**Comment by zakhenry** [comment]
nice one, thanks @kreuzerk !
