### ISSUE TITLE
Angular 9 peer version bump

### ISSUE THREAD

**Issue by mitschmidt** [angular-extensions/pretty-html-log#9]
Thanks for this useful and clean package, we just introduced it for jest debugging unit and integration tests in our large nx monorepo.

npm reports peer dependency warnings as we use angular >9:
```
npm[t5s] WARN @angular-extensions/pretty-html-log@2.0.0 requires a peer of @angular/common@^8.2.9 but none is installed. You must install peer dependencies yourself.
npm[t5s] WARN @angular-extensions/pretty-html-log@2.0.0 requires a peer of @angular/core@^8.2.9 but none is installed. You must install peer dependencies yourself.
```

We have not yet run into any issues, thereby suggesting to bump the peer dependency if there are no further concerns.

Thanks & sunny regards from Munich

**Comment by kreuzerk** [comment]
Hi, @mitschmidt wow. Glad to hear that it's useful and that you use the package in the organization. I will have a look at the issues this weekend. 👍
